# config/path.yml
data_dir: "Home Credit Dataset"

dirs:
  # Raw
  raw: "raw"

  # Intermediate
  train: "interim/train"
  test: "interim/test"

  # Modelling data
  modelling_train: "modelling/train"
  modelling_test: "modelling/test"
  
files:
  application: "application_train.csv"
  bureau: "bureau.csv"
  bureau_balance: "bureau_balance.csv"
  credit_card_balance: "credit_card_balance.csv"
  installments_payments: "installments_payments.csv"
  pos_cash_balance: "POS_CASH_balance.csv"
  previous_application: "previous_application.csv"
  columns_description: "HomeCredit_columns_description.csv"